---
all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
          ansible_host: 192.168.0.100  # pve1 — main server
        pve2:
          ansible_host: 192.168.0.150  # pve2
    qdevice:
      hosts:
        pi-qdevice:
          ansible_host: 192.168.0.199  # Pi — reserve this via DHCP reservation in router
          ansible_user: salman
          sshd_AllowUsers: salman
    lxc_hosts:
          hosts:
            pihole:
              ansible_host: 192.168.0.4
              ansible_user: root
            core_stack:
              ansible_host: 192.168.0.5
              ansible_user: root
            media_stack:
              ansible_host: 192.168.0.6
              ansible_user: root
            monitoring_stack:
              ansible_host: 192.168.0.7
              ansible_user: root
            automation_stack:
              ansible_host: 192.168.0.8
              ansible_user: root

  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
