version: "1"

networks:
  default:
    driver: bridge

services:


  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - /home/salman/media-stack/config/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - /home/salman/media-stack/config/sonarr:/config
      - /media/tv:/tv
      - /downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - /home/salman/media-stack/config/radarr:/config
      - /media/Movies:/movies
      - /downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /home/salman/media-stack/config/qbittorrent:/config
      - /downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - TZ=${TZ}
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/salman/media-stack/config/jellyfin/config:/config
      - /home/salman/media-stack/config/jellyfin/cache:/cache
      - /media/Movies:/data/Movies
      - /media/tv:/data/TVShows
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped


  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - "5055:5055"
    volumes:
      - /home/salman/media-stack/config/jellyseerr:/app/config
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - "7575:7575"
    volumes:
      - /home/salman/media-stack/config/homarr:/app/data/configs
      - /home/salman/media-stack/config/homarr/icons:/app/public/icons
      - /home/salman/media-stack/config/homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
